---
title: "teaching"
output: html_document
---
### Teaching

For many, anthropology is an esoteric, ivory-tower discipline with no real world applications. However, I aim to prove that the opposite is true. An anthropological perspective is an integral part of a college student’s education and will serve them well throughout their lives, as they become the next generation of student-scholars. I direct content towards a better understanding of the causes and consequences of human variation, equipping students with the skills to apply anthropological concepts to their daily lives. While some educators try to convince students of the fact of evolution, I concentrate instead on discussing why it matters that we evolved. The first day of my introductory courses is spent discussing the question, “What makes human distinctive?” As anthropologists, we can answer this question from both a biological and a cultural perspective. 

### Classes taught



Introduction to Anthropology   
Fundamentals of Biological Anthropology  
Introduction to World Prehistory  
Archaeology of North America  
Human Skeletal Anatomy   
Human Evolution: Violence and Virtues  
Learning R for Statistical Computing  


